version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3050:3050"
    volumes:
      - ./frontend:/app:delegated
      - node_modules_frontend:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - .env 
    ports:
      - 9001:9000
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - chromadb
    volumes:
      - ./backend:/app

  chromadb:
    image: chromadb/chroma:0.5.23 
    ports:
      - "8002:8000"
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

volumes:
  chroma_data:
  node_modules_frontend: