"""create knowledge_bases indexing_jobs query_history tables

Revision ID: 56a5edd34a0d
Revises: 081dc6dd7927
Create Date: 2026-08-01 19:05:29.114822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a5edd34a0d'
down_revision: Union[str, None] = '081dc6dd7927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indexing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.add_column('documents', sa.Column('knowledge_base_id', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('category', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('language', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunks', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'chunks')
    op.drop_column('documents', 'pages')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'size')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'knowledge_base_id')
    op.drop_table('indexing_jobs')
    op.drop_table('query_history')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
